<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Temas de Interes - Juan Sandoval Asociados</title>
    <meta property="og:type" content="website">
    <link rel="icon" type="image/svg+xml" sizes="155x150" href="assets/img/logo-slider.svg">
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kaushan+Script">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Thasadith">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="assets/css/styles.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">
</head>

<body>
<nav class="navbar navbar-light navbar-expand-md sticky-top" style="height: 25px;padding: 0px;background: #003869;">
    <div class="container-fluid">
        <div class="col text-right">
            <div class="row text-right">
                <div class="col" style="font-size: 4px;padding-left: 15px;padding-right: 5px;">
                    <h1 style="font-size: 12px;color: rgb(255,255,255);font-family: Thasadith, sans-serif;margin-top: 8px;"><i class="fa fa-phone" style="color: rgb(255,214,0);"></i>&nbsp;56 1164 8763&nbsp; |&nbsp; &nbsp;<i class="fa fa-envelope-o" style="color: rgb(255,214,0);"></i>&nbsp;contactanos@juansandoval.com.mx</h1>
                </div>
            </div>
        </div>
    </div>
</nav>
<nav class="navbar navbar-light navbar-expand-sm sticky-top bg-light d-flex justify-content-center" id="mainNav" style="border-bottom: 4px solid #e1b218;padding-top: 0px;padding-bottom: 10px;">
    <div class="container-fluid"><a class="navbar-brand" style="margin-left: 0px;padding-left: 0px;padding-right: 0px;margin-right: 0px;" href="index2.php#header"><img src="assets/img/logo%20header.svg" style="width: 150px;color: rgb(254, 209, 54);"></a><button data-toggle="collapse" data-target="#navbarResponsive" class="navbar-toggler navbar-toggler-right" type="button" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
        <div class="collapse navbar-collapse" id="navbarResponsive" style="font-size: 20px;margin-top: 5px;padding-top: 0px;">
            <ul class="navbar-nav navbar-nav-scroll mx-auto text-uppercase">
                <li class="nav-item"><a class="nav-link text-capitalize js-scroll-trigger" href="index2.php#quienes" style="font-family: Thasadith, sans-serif;color: rgb(0,56,105);">¿quiénes somos?</a></li>
                <li class="nav-item"><a class="nav-link text-capitalize js-scroll-trigger" href="index2.php#valores" style="color: rgb(0,56,105);font-family: Thasadith, sans-serif;">nuestros valores</a></li>
                <li class="nav-item"><a class="nav-link text-capitalize js-scroll-trigger" href="index2.php#servicios" style="color: rgb(0,56,105);font-family: Thasadith, sans-serif;">Nuestros servicios</a></li>
                <li class="nav-item"><a class="nav-link text-capitalize js-scroll-trigger" href="#" style="font-family: Thasadith, sans-serif;color: rgb(0,56,105);">temas de interés</a></li>
                <li class="nav-item"><a class="nav-link text-capitalize js-scroll-trigger" href="index2.php" style="color: rgb(0,56,105);font-family: Thasadith, sans-serif;">Contactanos</a></li>
            </ul>
        </div>
    </div>
</nav>
<header data-aos="fade" data-aos-duration="900" class="masthead" style="background: url(&quot;assets/img/slider1.jpg&quot;) center / cover no-repeat;">
<div class="container" id="header" style="max-width: 100%;background: rgba(10,10,10,0.49);">
        <div class="intro-text" style="padding-top: 70px;padding-bottom: 200px;">
            <div class="intro-lead-in" style="margin-bottom: 0px;margin-top: 0px;padding-top: 15px;padding-bottom: 15px;margin-right: 100px;margin-left: 100px;border-top-width: 1px;border-top-style: solid;border-bottom-width: 1px;border-bottom-style: solid;"><span class="text-break text-justify" style="font-size: 40px;margin-bottom: 10px;margin-top: 10px;padding-top: 10px;padding-bottom: 10px;font-family: Thasadith, sans-serif;height: auto;text-align: center;"></span>
                <p style="font-size: 40px;font-family: Thasadith, sans-serif;">TEMAS DE INTERES</p>
            </div>
        </div>
    </div>
</header>
<section data-aos="fade-down" id="quienes" class="about-us" style="padding-top: 100px;padding-bottom: 150px;">
<div class="container">
        <div class="row">
            <div class="col" style="border-bottom: 1px solid rgb(0,56,105);padding-bottom: 15px;"><img src="assets/img/bullet.svg" style="width: 16px;transform: rotate(180deg);"><a href="index.php" style="font-family: Thasadith, sans-serif;font-weight: 700;color: rgb(0,56,105);">&nbsp;Regresar a Home</a></div>
        </div>
        <div class="row" style="padding-top: 50px;border-bottom: 1px solid rgb(0,56,105) ;">
            <div class="col-xl-4">
                <div class="row">
                    <div class="col flex-column flex-column">
                        <ul class="nav nav-tabs flex-column">
                            <li class="nav-item"><a class="nav-link" href="#" style="background: rgba(255,255,255,0);border-style: none;font-size: 25px;font-weight: 700;font-family: Thasadith, sans-serif;color: rgb(0,56,105);" data-toggle="collapse" data-target="#collapseHipotecario" aria-expanded="false" aria-controls="collapseExample">Derecho Hipotecario</a></li>
                            <li class="nav-item"><a class="nav-link" href="#" style="background: rgba(255,255,255,0);border-style: none;font-size: 25px;font-weight: 700;font-family: Thasadith, sans-serif;color: rgb(0,56,105);" data-toggle="collapse" data-target="#collapseCivil" aria-expanded="false" aria-controls="collapseExample">Derecho Civil</a></li>
                            <li class="nav-item"><a class="nav-link" href="#" style="background: rgba(255,255,255,0);border-style: none;font-size: 25px;font-weight: 700;font-family: Thasadith, sans-serif;color: rgb(0,56,105);" data-toggle="collapse" data-target="#collapseMercantil" aria-expanded="false" aria-controls="collapseExample">Derecho Mercantil</a></li>
                            <li class="nav-item"><a class="nav-link" href="#" style="background: rgba(255,255,255,0);border-style: none;font-size: 25px;font-weight: 700;font-family: Thasadith, sans-serif;color: rgb(0,56,105);" data-toggle="collapse" data-target="#collapseFamiliar" aria-expanded="false" aria-controls="collapseExample">Derecho Familiar</a></li>
                            <li class="nav-item"><a class="nav-link" href="#" style="background: rgba(255,255,255,0);border-style: none;font-size: 25px;font-weight: 700;font-family: Thasadith, sans-serif;color: rgb(0,56,105);" data-toggle="collapse" data-target="#collapsePenal" aria-expanded="false" aria-controls="collapseExample">Derecho Penal</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col pulse animated collapse" id="collapseHipotecario">
            <h1 style="color: rgb(225,178,24);font-family: Thasadith, sans-serif;">Derecho Hipotecario</h1>
                <h2 style="color: rgb(0,56,105);font-family: Thasadith, sans-serif;font-size: 20px;text-align: justify;">Conjunto de normas del Derecho civil que regulan la inscripción en el Registro de la Propiedad y publicidad de los actos de reconocimiento, transmisión, constitución, modificación, gravamen y extinción del dominio sobre bienes inmuebles y derechos reales sobre los mismos.<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;">Es la parte del Derecho que estudia la adquisición, transmisión, modificación y extinción de los derechos sobre bienes inmuebles en cuanto éstos se reflejan en el Registro de la propiedad. Por lo tanto, y en cierto sentido, el Derecho hipotecario podría denominarse Derecho inmobiliario, en cuanto rama jurídica dedicada a las normas sobre<br>inmuebles. Asimismo, y en otro sentido, podría el Derecho hipotecario denominarse Derecho registral, en cuanto rama jurídica especializada en el dinamismo de los derechos sobre inmuebles reflejado en el referido registro. La denominación Derecho inmobiliario registral, posiblemente la más adecuada, ha sido muchas veces postergada ante la de Derecho hipotecario, de más rancia tradición al enlazar con el nombre de la ley especial que, antes de la promulgación del vigente Código civil, desmarcó de éste la materia inmobiliaria registral, sin perjuicio de que ésta pueda considerarse como rama del tronco común del Derecho civil.<br><br>El Derecho inmobiliario es el conjunto de normas y leyes que regula todas las operaciones que pueden realizarse sobre los bienes que la ley define como raíces -aquellos que por sus características físicas no pueden desplazarse del lugar en que se encuentran-, tanto entre ciudadanos como entre un particular y la administración pública. Es<br>decir, se encarga de regular todas las transacciones inmobiliarias: la forma en que se crean, transmite, modifican, adquieren o extinguen los derechos que una persona física o jurídica tiene sobre una propiedad inmueble o parte de ella, así como de los impuestos y gravámenes que debe hacer frente por cada una de estas operaciones. También abarca los aspectos referentes a la gestión de estos inmuebles, es decir, licencias urbanas, de obras o las normas que regulan las comunidades de vecinos.<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;">Como ocurre con otras ramas jurídicas, el Derecho inmobiliario es una materia transversal y su regulación se realiza a través de varias leyes que corresponden a distintas ramas del Derecho. Así, partiendo de la Constitución Española como marco jurídico, encontraremos que los derechos y deberes que afectan a las personas con derechos de cualquier tipo sobre un bien inmueble están regulados en distintos cuerpos legales: desde el Código Civil al Código Mercantil cuando sea&nbsp;de&nbsp;aplicación, además de leyes específicas como la Ley Hipotecaria o leyes tributarias que determinen los impuestos o gravámenes que recaen&nbsp;sobre un inmueble (IBI, Impuesto de Transmisiones Patrimoniales y Actos Jurídicos Documentados, etc.).&nbsp;</h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;"> El ámbito de aplicación del Derecho inmobiliario, por tanto, será la regulación de todos aquellos actos y contratos que afecten a un bien inmueble. Así, en general, el Derecho inmobiliario aborda:<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 13px;">La regulación de los derechos reales sobre un bien inmueble&nbsp;<br></label>Se dividen básicamente en derecho de propiedad y derechos limitativos del dominio. El Derecho inmobiliario regula qué es la propiedad y los derechos que otorga, cómo se adquiere, se comparte o se transmite. En cuanto a los derechos limitativos, regula situaciones como el usufructo,&nbsp;la habitación o la servidumbre de un bien.<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>La compraventa de inmuebles&nbsp;u operaciones inmobiliarias.&nbsp;</strong><br></label>Este proceso requiere cumplir trámites previos para garantizar la validez de la operación: será necesario comprobar la situación urbanística, registral y administrativa de una finca antes de su&nbsp;compraventa, preparar contratos previos -como el de arras o el de opción de compra-, o liquidar los impuestos que devenguen antes y después de la compraventa.<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;">La compraventa de inmuebles u operaciones inmobiliarias.&nbsp;<br></label>&nbsp;En el caso de un edificio en el que la propiedad de los pisos y locales corresponde a distintas personas, será necesario constituir una comunidad para tomar las decisiones pertinentes y cumplir las obligaciones legales.<br></h2>
            </div>
            <div class="col collapse" id="collapseCivil">
                <h1 style="color: rgb(225,178,24);font-family: Thasadith, sans-serif;">Derecho Civil</h1>
                <h2 style="color: rgb(0,56,105);font-family: Thasadith, sans-serif;font-size: 20px;text-align: justify;">El Derecho Civil en México se ocupa de regular los derechos y obligaciones de los individuos desde el momento de su concepción hasta su muerte. <br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;">Para regular las figuras o relaciones jurídicas del Derecho Civil, en nuestro país existe un código civil para cada estado de la República Mexicana y un Código Civil Federal. En esencia estos códigos civiles contienen&nbsp;disposiciones muy similares, sin embargo, se recomienda consultar la legislación del estado del lugar del domicilio de las personas físicas cuando se trate de casos relacionados con el estado o capacidad de dichas personas físicas. Tratándose de casos relativos a la constitución, régimen y extinción de derechos reales sobre inmuebles, así como los contratos de arrendamiento y de uso temporal de tales bienes, y los bienes muebles, se recomienda consultar la legislación del lugar de ubicación de esos bienes. Y finalmente es recomendable consultar la legislación del lugar en donde se producen los actos jurídicos.<br><br>El Derecho Civil es la rama del derecho privado que contempla temas relativos a las personas, los bienes, las sucesiones, las obligaciones y los contratos. Las controversias que se susciten en relación con estos temas serán del conocimiento de los tribunales judiciales competentes en materia civil.<br><br>La ley dispone que por parte del Estado para conocer o intervenir en alguno de estos temas de Derecho Civil, según sea el caso concreto, se encuentran las autoridades judiciales, las autoridades del Registro Civil, notarios públicos, corredores públicos, actuarios o el Registro Público de la Propiedad.<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 13px;">Las personas.&nbsp;<br></label>&nbsp;Los códigos civiles disponen que las personas físicas adquieren su capacidad jurídica con el nacimiento y la pierden con su muerte, la ley dispone además que desde el momento en que un individuo es concebido, entra bajo la protección de la ley y se tiene por nacido para efectos legales. La minoría de edad, el estado de interdicción, y otras incapacidades jurídicas, son restricciones a la personalidad jurídica, sin embargo, los incapaces pueden ejercitar sus derechos o contraer obligaciones por medio de sus representantes. Una persona se distingue de otra por el nombre, el domicilio, los actos del estado civil y el patrimonio. Los actos del estado civil de las personas se hacen constar ante la autoridad del Registro Civil que es llamada Oficial o Juez del Registro Civil según el estado de la República Mexicana de que se trate. Estos actos son por ejemplo el registro del nacimiento, el matrimonio, el divorcio, la adopción, entre otros.<br>Las disposiciones del código civil además de regular a las personas físicas, dan tratamiento legal a las personas jurídicas conocidas en esta materia como asociaciones y sociedades civiles. Conviene mencionar que no se debe confundir a estas personas jurídicas del derecho civil con las sociedades mercantiles las cuales están reguladas por el derecho mercantil.<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Los Bienes.&nbsp;</strong><br></label>&nbsp;El Derecho Civil se ocupa de la protección y respeto de los bienes muebles y de los bienes inmuebles. La ley regula la forma cómo estos bienes se adquieren, su uso, goce, disfrute, la forma de transmitirlos y los conflictos derivados de ellos. En relación con los bienes están los derechos y obligaciones relativos a la propiedad y a la posesión.<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;">La Propiedad.&nbsp;<br></label>&nbsp;En virtud de la propiedad, una persona tiene derecho a usar y disponer de sus bienes de acuerdo con la ley. El Estado, en caso de interés público y otorgando una indemnización al individuo podrá usar, disfrutar o disponer de la propiedad de una persona, como es el caso de la expropiación por causa de utilidad pública. La ley establece como formas de adquirir la propiedad: los contratos, la sucesión, la usucapión, la apropiación y la accesión.<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;">La Posesión.&nbsp;<br></label>&nbsp;La posesión no es lo mismo que la propiedad, la ley distingue un término del otro. La posesión es el hecho mediante el cual una persona tiene el poder de un bien o derecho sobre el cual realiza actos de uso, goce y disfrute. Una persona puede tener la posesión de un bien mueble o inmueble, o de un derecho, sin ser la propietaria. Como por ejemplo en el caso del contrato de arrendamiento mediante el cual el arrendador concede el uso y goce de una cosa al arrendatario; el arrendatario poseerá la cosa, pero el arrendador conservará la propiedad. La posesión de una cosa o derecho puede adquirirse de buena fe, como en virtud de un contrato de arrendamiento; o bien la posesión<br>puede adquirirse de mala fe, como por ejemplo cuando no se posee título alguno.<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;">Las Obligaciones.&nbsp;<br></label>&nbsp;El Derecho Civil regula también las obligaciones y establece los efectos jurídicos que producen. La obligación es el vínculo jurídico entre dos personas, una llamada acreedor y la otra llamada deudor. Por virtud de las obligaciones, el acreedor tiene derecho a exigir del deudor de forma coactiva el cumplimiento de una prestación; y el deudor realiza coactivamente el cumplimiento de una prestación a la cual tiene derecho el acreedor. Un claro ejemplo lo tenemos en el caso de la compraventa, el cual es el contrato por el cual el vendedor se obliga a transferir la propiedad de una cosa o de un derecho, y el comprador a su vez se obliga a pagar por ellos un precio cierto y en dinero. Ahora bien, la ley dispone que las obligaciones pueden ser de dar, hacer o no hacer. Nuestro derecho establece como formas de transmisión de las obligaciones: la cesión de derechos, la cesión de deudas y la subrogación. puede adquirirse de mala fe, como por ejemplo cuando no se posee título alguno.<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;">Los Contratos.&nbsp;<br></label>&nbsp;Los códigos civiles se refieren a los contratos como los convenios que producen o transfieren las obligaciones y derechos. Y los convenios son los acuerdos de dos o más personas para crear, transferir, modificar o extinguir las obligaciones. La ley prevé cuáles son los elementos de existencia y de validez de los contratos. La falta de los elementos de existencia de los contratos produce la inexistencia del contrato; y la falta de los elementos de validez de los contratos produce la nulidad del contrato. Los contratos previstos por la ley reciben en la doctrina el nombre de contratos nominados como son los contratos de compraventa, arrendamiento, subarriendo, comodato, depósito, mandato, prestación de servicios profesionales, obra a precio alzado, hospedaje, asociación civil, sociedad civil, aparcería rural, renta vitalicia, compra de esperanza, fianza, prenda e hipoteca. Algunos de estos contratos requieren para su existencia o validez cumplir con ciertas formalidades que la ley establece por ejemplo algunos contratos deberán celebrarse por las partes ante testigos, notario público o deberán ser inscritos en el Registro Público de la Propiedad, como por ejemplo en el caso del contrato de compraventa de bienes inmuebles la ley dispone que el contrato sea celebrado ante notario público e inscrito en el Registro Público para que sea válido y sea reconocido<br>frente a terceros.<br><br>En la práctica se puede dar el caso de que pese a la existencia de un contrato en el cual fueron estipulados los derechos y obligaciones de las partes, una de ellas o todas las partes contratantes incumplan en forma total o parcial con el contrato, en este caso las partes podrán exigirse el cumplimiento de las obligaciones pactadas o bien rescindir el contrato y puede hacerse de pleno derecho, sin necesidad de acudir ante las autoridades judiciales según se haya estipulado en el contrato o bien acudiendo ante los tribunales judiciales competentes.<br></h2>
            </div>
            <div class="col collapse" id="collapseMercantil">
                <h1 style="color: rgb(225,178,24);font-family: Thasadith, sans-serif;">Derecho Mercantil</h1>
                <h2 style="color: rgb(0,56,105);font-family: Thasadith, sans-serif;font-size: 20px;text-align: justify;">En México, el Derecho Mercantil al igual que el Derecho Civil pertenece al Derecho Privado. Existen uno al lado del otro, de forma separada ya que el Derecho Civil regula las relaciones jurídicas privadas en general y el Derecho Mercantil regula las relaciones jurídicas más específicas, aquellas que se dan entre comerciantes y las actividades que se dan en el comercio. El Derecho Mercantil se define como el conjunto de normas jurídicas que regulan a las personas, las relaciones, los actos y las cosas que tienen que ver con el comercio. <br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;">En este sentido, es importante definir cuáles son las disposiciones aplicables en materia de derecho mercantil, quiénes son considerados como comerciantes para efectos del derecho mercantil y qué son los actos de comercio, entre otros temas comprendidos por esta rama del derecho.<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 13px;">Disposiciones Aplicables.&nbsp;<br></label>&nbsp;En México, los actos de comercio, son regulados por el Código de Comercio y demás leyes mercantiles y a falta de disposiciones en estas leyes, serán aplicables las disposiciones contenidas en el Código Civil Federal. Algunas de estas leyes mercantiles son: Ley de Comercio Exterior; Ley de Concursos Mercantiles; Ley de Instituciones de Crédito; Ley General de Sociedades Mercantiles; Ley General de Títulos y Operaciones de Crédito; Ley<br>Sobre el Contrato de Seguro, entre otras.<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Comerciantes.&nbsp;</strong><br></label>&nbsp;De acuerdo con el Código de Comercio se consideran comerciantes tanto las personas físicas y morales con las siguientes consideraciones:<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">1. Las personas que de acuerdo con la ley tienen capacidad para contratar y obligarse, que hagan del comercio su ocupación ordinaria y a quienes las leyes no les prohíben expresamente la profesión de comercio. </h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">2.Las sociedades constituidas conforme a las leyes mercantiles. </h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">3.Las sociedades extranjeras, sus agencias y sucursales, que ejerzan actos de comercio en México.<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;">Esto es, los comerciantes son aquellas personas físicas o morales que hacen del comercio su profesión habitual. No obstante ello, se puede dar el supuesto de que cualquier persona física o moral con o sin establecimiento físico, eventual o accidentalmente, realice alguna operación de comercio y aunque no sea considerada en derecho como comerciante, por el hecho de realizar esa operación de comercio, quedaría sujeta a las leyes mercantiles. Los comerciantes tienen como obligaciones legales: inscribir en el Registro Público de Comercio los documentos cuya autenticidad deba hacerse notoria; mantener un sistema de contabilidad; y conservar la correspondencia relacionada<br>con el giro de comerciante.<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Actos de Comercio</strong><br></label>. Los actos de comercio son aquellos actos jurídicos celebrados por personas físicas o morales, comerciantes o no, que produzcan efectos jurídicos regulados por el derecho mercantil. El Código de Comercio enuncia cuáles son los actos de comercio contemplados por la ley. Los reproducimos a continuación:<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">1.&nbsp; Las adquisiciones, enajenaciones y alquileres verificados con propósito de especulación comercial, de mantenimientos, artículos, muebles o mercaderías, en estado natural, después de trabajados o labrados.<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">2. Las compras y ventas de bienes inmuebles, cuando se hagan con propósito de especulación comercial.<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">3.&nbsp;Las compras y ventas de porciones, acciones y obligaciones de las sociedades mercantiles.<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">4. Los contratos relativos y obligaciones del Estado u otros títulos de crédito corrientes en el comercio.<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">5. Las empresas de abastecimientos y suministros.<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">6.&nbsp;<strong>Las empresas de construcciones, y trabajos públicos y privados.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">7. Las empresas de fábricas y manufacturas.<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">8.&nbsp;<strong>Las empresas de trasportes de personas o cosas, por tierra o por agua; y las empresas de turismo.</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">9.&nbsp;<strong>Las librerías, y las empresas editoriales y tipográficas.</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">10.&nbsp;<strong>Las empresas de comisiones, de agencias, de oficinas de negocios comerciales, casas de empeño y establecimientos de ventas en pública almoneda.</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">11.<strong>Las empresas de espectáculos públicos.</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">12.&nbsp;<strong>Las operaciones de comisión mercantil.</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">13.&nbsp;<strong>Las operaciones de mediación de negocios mercantiles</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">14.&nbsp;<strong>Las operaciones de bancos</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">15.&nbsp;<strong>Todos los contratos relativos al comercio marítimo y a la navegación interior y exterior.</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">16.&nbsp;<strong>Los contratos de seguros de toda especie.</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">17.&nbsp;<strong> Los depósitos por causa de comercio.</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">18.&nbsp;<strong>Los depósitos en los almacenes generales y todas las operaciones hechas sobre los certificados de depósito y bonos de prenda.</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">19.&nbsp;<strong>Los cheques, letras de cambio o remesas de dinero de una plaza a otra.</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">20.&nbsp;<strong>* Los vales u otros títulos a la orden o al portador, y las obligaciones de los comerciantes, a no ser que se pruebe que se derivan de una causa extraña al comercio</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">21.&nbsp;&nbsp;<strong>Las obligaciones entre comerciantes y banqueros, si no son de naturaleza esencialmente civil.</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">22.&nbsp;<strong>Los contratos y obligaciones de los empleados de los comerciantes en lo que concierne al comercio del negociante que los tiene a su servicio.</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">23.&nbsp;<strong>&nbsp;La enajenación que el propietario o el cultivador hagan de los productos de su finca o de su cultivo.</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">24.&nbsp;<strong>Las operaciones contenidas en la Ley General de Títulos y Operaciones de Crédito.</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">25.&nbsp; Cualesquiera otros actos de naturaleza análoga a los expresados.<br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><strong>En caso de duda si un acto es de comercio o no, un árbitro judicial será quien lo determine. Por otro lado, no se consideran actos de comercio la compra de artículos para uso o consumo del comerciante o de su familia.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Registro Público de Comercio</strong><br></label><strong>El Registro Público de Comercio es una institución de la cual no se puede prescindir en el Derecho Mercantil, toda vez que los comerciantes están obligados a inscribir los documentos que deben hacerse notorios, como por ejemplo la escritura constitutiva tratándose de sociedades mercantiles, algunas clases de contratos y demás actos mercantiles en los casos que así lo establezca la ley.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Contratos Mercantiles.&nbsp;</strong><br></label><strong>Los contratos mercantiles son los convenios que producen o transfieren obligaciones y derechos de naturaleza mercantil. Entre los contratos mercantiles regulados por las disposiciones de naturaleza mercantil encontramos: agencia, cesión de créditos comerciales, comisión mercantil, concesión mercantil, consignación mercantil, compraventa mercantil, permuta mercantil, diversos contratos de seguro, diversos contratos de transporte, depósito mercantil, fianza, fideicomiso, garantía, suministro, tiempo compartido y otros.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Comercio Electrónico.&nbsp;</strong><br></label><strong>En los actos de comercio y en la formación de los mismos puedan emplearse medios electrónicos, ópticos o de cualquier otra tecnología. En los actos de comercio electrónico se aplicarán las disposiciones del Código de Comercio, además de lo dispuesto en los Tratados Internacionales de los que México sea parte. Además, las actividades que se celebren con motivo del comercio electrónico, se someterán en su interpretación y aplicación a los principios de neutralidad tecnológica, autonomía de la voluntad, compatibilidad internacional y equivalencia funcional del mensaje de datos con documentos no electrónicos y de la firma electrónica en relación con la firma autógrafa.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Sociedades Mercantiles.&nbsp;</strong><br></label><strong>Las Sociedades Mercantiles son reconocidas como personas morales, sujetos de derecho con capacidad jurídica, patrimonio, nombre, domicilio y nacionalidad propios, distintos de la persona de los socios que la integran. Las Sociedades Mercantiles son aquellas que se constituyan en alguna de las formas reconocidas por la Ley General de Sociedades Mercantiles y podrán realizar los actos de comercio necesarios para el cumplimiento de su objeto social, salvo lo expresamente prohibido por las leyes y los estatutos sociales. Son Sociedades Mercantiles reconocidas por la Ley General de Sociedades Mercantiles: la Sociedad en Nombre Colectivo; la Sociedad en Comandita Simple; la Sociedad de Responsabilidad Limitada; la Sociedad Anónima; la Sociedad en Comandita por Acciones; la Sociedad Cooperativa; y la Sociedad por Acciones Simplificada. Las Sociedades Mercantiles deberán constituirse mediante contrato social otorgado en escritura, ante notario o corredor público e inscribirse en el Registro Público de Comercio para que produzcan efectos legales y sean reconocidos por terceros. La Ley General de Sociedades Mercantiles establece disposiciones comunes aplicables a todos los tipos de sociedades como aquellas que se refieren a los requisitos de la escritura constitutiva, la razón o denominación social, el domicilio, el objeto social, la forma de administrar la sociedad, la representación de la sociedad, entre otros, pero también dispone de apartados aplicables específicamente a cada uno de los tipos de sociedades.&nbsp;</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Sociedades Irregulares</strong><br></label><strong>Las sociedades irregulares son aquellas que no cumplen los requisitos exigidos por la ley en cuanto a su constitución y funcionamiento. Por ejemplo, aquellas que no se hacen constar en escritura constitutiva, que no se han constituido ante notario público o bien que la escritura no se encuentra inscrita en el Registro Público de Comercio. No obstante, su constitución irregular, estas sociedades gozan de personalidad jurídica distinta de la de los socios que las constituyen. Y las relaciones internas de estas sociedades se regirán por el contrato social respectivo, y en su defecto por la Ley General de Sociedades Mercantiles según la clase de sociedad de que se trate. En el caso de terceros que hayan contratado con una sociedad irregular, no sabiendo que dicha sociedad tiene tal carácter, podrán exigirle el cumplimiento de las obligaciones a los representantes de esa sociedad, además de la responsabilidad penal en que pudieran haber incurrido dichos representantes cuando los terceros resulten perjudicados.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Titulos y Operaciones de Crédito.&nbsp;</strong><br></label><strong>Los títulos de crédito reconocidos por la ley son: el pagaré, la letra de cambio, el cheque, el certificado de depósito y bono de prenda. Los títulos de crédito son actos de comercio, cosas mercantiles y son los documentos necesarios para ejercitar el derecho literal que en ellos se consigna. Este derecho literal hace referencia al derecho y a la obligación contenidos en el texto del documento. Por ejemplo, el derecho que tiene el beneficiario de un pagaré a que le sea pagada la cantidad a que se ha obligado el suscriptor del mismo. Los títulos de crédito pueden transmitirse de una persona a otra, a esto se le conoce como circulación, la cual se realiza a través del endoso y mediante la entrega material del documento. La emisión, expedición, endoso, aval, aceptación y demás operaciones que se consignen en los títulos de crédito son considerados como actos de comercio. Los títulos de crédito son independientes del contrato que les haya dado origen, de tal forma que, si un contrato que le dio origen a un título de crédito es afectado de nulidad, no por ello el título es considerado nulo. La ley establece cuáles son los elementos, requisitos, emisión, circulaciones, derechos y obligaciones de los beneficiarios y de los emisores de los títulos de crédito. Así como los presupuestos, requisitos y acciones procesales para el caso de incumplimiento. Los títulos y operaciones de crédito, se rigen por lo dispuesto en la Ley de Títulos y Operaciones de Crédito, por la legislación mercantil general, por los usos bancarios y mercantiles; y por Código Civil del Distrito Federal.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Concurso Mercantil.&nbsp;</strong><br></label><strong>Mediante el procedimiento de concurso mercantil, se declara en concurso al comerciante que ha incumplido con sus obligaciones de pago a dos o más acreedores distintos y bajo las condiciones previstas en la Ley de Concursos Mercantiles. El procedimiento de concurso mercantil puede ser solicitado por: el propio comerciante, el acreedor o el Ministerio Público. Mediante este procedimiento se busca evitar que el incumplimiento de las obligaciones de pago del comerciante ponga en riesgo la existencia de la empresa, y que además se lesione a los acreedores, a sus clientes, proveedores y empleados. El procedimiento de concurso mercantil comprende dos fases, la etapa de conciliación y la etapa de quiebra. Mediante la fase de conciliación, el objetivo es la conservación de la empresa del comerciante mediante un convenio que suscriba con los acreedores reconocidos. La finalidad de la quiebra es la venta de la empresa del comerciante, de sus unidades productivas o de los bienes que la integran para el pago a los acreedores reconocidos.</strong><br></h2>
            </div>
            <div class="col pulse animated collapse" id="collapseFamiliar">
            <h1 style="color: rgb(225,178,24);font-family: Thasadith, sans-serif;">Derecho Familiar</h1>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 13px;">Matrimonio.<br></label><strong>Una de las instituciones fundamentales en el derecho de familia es el matrimonio, el cual es la unión legal de dos personas que reciben el nombre de cónyuges, quienes consienten en realizar una comunidad de vida, de ayuda mutua y toman de manera libre, responsable, voluntaria e informada las decisiones reproductivas que se ajustan a su proyecto de vida, incluyéndose la posibilidad de procrear o adoptar.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Divorcio.</strong><br></label><strong>Cuando cualquiera de los cónyuges o ambos no desean continuar en matrimonio, pueden de forma individual o de común acuerdo, solicitar o promover por la vía administrativa o judicial según resulte procedente, la disolución del matrimonio. La forma de disolver el vínculo matrimonial es el divorcio y deja a los cónyuges en aptitud de contraer otro matrimonio.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Concubinato</strong><br></label><strong>Resulta conveniente mencionar que una figura que ha cobrado importancia en cuanto a su reconocimiento en el derecho de familia y a los derechos y obligaciones que derivan de esta, es la figura del concubinato consistente en la unión entre dos personas, llamadas concubinos que sin contraer matrimonio y sin impedimento para contraerlo, hacen vida en común de manera constante y permanente por un periodo de tiempo. Sin embargo, no será necesario el transcurso del periodo de tiempo si reunidos los demás requisitos los concubinos tienen un hijo en común.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Filiación:&nbsp;</strong><br></label><strong>Nuestro Derecho Mexicano destaca una figura importante: la filiación, siendo esta el vínculo jurídico que existe entre dos personas en la que una desciende de la otra por hechos biológicos y/o actos jurídicos. La filiación proporciona identidad al menor e implica las responsabilidades de guarda, custodia y educación.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Paternidad y Maternidad.&nbsp;</strong><br></label><strong>Como consecuencia de la filiación, la ley hace referencia a la paternidad y a la maternidad que es la relación jurídica que se da entre padres e hijos; la primera es la relación jurídica entre el padre y sus hijos y la segunda es la relación entre la madre y sus hijos; en ambos casos independientemente de que los padres estén casados o no. El hecho de que la ley reconozca la paternidad o maternidad independientemente de que los padres se encuentren casados o no es la garantía que el legislador otorga a los hijos en atención al ejercicio y goce de los derechos de igualdad y no discriminación en las relaciones paterno filiales. La filiación no debe estar sujeta a condiciones que no atañen a los hijos. Por virtud de la filiación los padres son responsables en condición de igualdad frente a sus hijos, la ley protege el interés superior del hijo. Tenemos además que el reconocimiento de la paternidad o maternidad se refiere a que una persona pueda ser reconocida como hijo por el padre o la madre, respectivamente. Este reconocimiento puede ser voluntario o a través del ejercicio de acciones legales. Una vez que se da el reconocimiento de la paternidad o maternidad, la condición de hijo no se pierde sino por sentencia judicial que así lo determine, como resultado de la impugnación de la paternidad.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Adopción</strong><br></label><strong>&nbsp;La adopción, es otra forma de la cual puede resultar la filiación. La adopción sustituye a la filiación de origen, el adoptado deja de pertenecer a su familia natural y por tanto se extingue el parentesco con los integrantes de esta y sus efectos jurídicos. El adoptado tiene en la familia del adoptante los mismos derechos y obligaciones de un hijo y los impedimentos matrimoniales se extienden a la familia del adoptante. La ley establece los requisitos legales para la adopción, velando para que sea benéfica para los adoptados, previa valoración psicológica y socioeconómica de los adoptantes.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Patria Potestad.&nbsp;</strong><br></label><strong>En el derecho de familia también tenemos a la institución jurídica de la patria potestad que es de interés público y vela por el interés superior y la protección del menor. La patria potestad busca garantizar y proteger el desarrollo del menor en sus aspectos físico, moral y social, su guarda y custodia, la administración de sus bienes y su representación. Surge ante la necesidad que tienen los menores de ser protegidos, educados, alimentados y representados, estas obligaciones recaen de manera natural sobre los padres y a falta o imposibilidad de estos, sobre los abuelos. La patria potestad es por lo tanto el conjunto de derechos y deberes que corresponde a los padres y en su defecto a los abuelos sobre los menores no emancipados. La patria potestad es irrenunciable, sin embargo, ésta puede acabarse, perderse o suspenderse en los supuestos que señala la ley.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Guardia y Custodia.</strong><br></label><strong>Cuando se da el caso de separación o divorcio de los padres de los menores, ambos progenitores conservarán la patria potestad y deberán de cumplir con sus obligaciones parentales, sin embargo, los padres deben llegar a un acuerdo sobre cuál de ellos tendrá la guarda y custodia o bien si esta será compartida. Si los padres no llegan a un acuerdo, la decisión de guarda y custodia la determinará un juez en atención a aquel progenitor que tenga capacidad de proporcionar las mejores condiciones para el desarrollo integral del menor, decidiendo siempre en base al interés superior de la niñez; la decisión del juez también puede ser en el sentido de una guarda y custodia compartida en cuyo caso ambos padres compartirán los derechos y responsabilidades en la educación, formación, manutención y representación de los menores en igualdad de condiciones o de manera proporcional según se haya establecido judicialmente.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Tutela</strong><br></label><strong>El legislador en las disposiciones relativas al derecho de familia incluye la figura jurídica de la tutela que tiene por objeto la guarda y protección de la persona y bienes de los que no estando sujetos a patria potestad tienen incapacidad natural y legal como es el caso de los menores, o solamente incapacidad legal, para gobernarse y obligarse por sí mismos. La tutela es un cargo de interés público. El tutor puede ser inhabilitado o separado de su cargo, o bien la tutela puede extinguirse cuando se dan los supuestos que señala la ley.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Alimentos.&nbsp;</strong><br></label><strong>Aunado a las instituciones jurídicas a las que hemos hecho referencia en los párrafos anteriores, el derecho de familia se refiere a la obligación de dar alimentos y el derecho a pedirlos. Los alimentos comprenden la comida, el vestido, la habitación y la asistencia en caso de enfermedad, tratándose de menores comprenden además los gastos necesarios para la educación y para proporcionarle algún oficio, arte, profesión honestos y adecuados al sexo y circunstancias personales del alimentista. Se trata de una obligación de orden público, recíproca, inherente a la filiación y al parentesco. El que da alimentos tiene a su vez el derecho de pedirlos. El derecho a recibir alimentos es personalísimo, irrenunciable, intransmisible e inembargable. La obligación alimentaria es igualmente personalísima. La ley establece que los alimentos han de ser proporcionales a la posibilidad del que debe darlos y a las necesidades del que debe recibirlos. El deudor alimentario por virtud de su obligación cumple al pagar los alimentos o al integrar a la familia al acreedor alimentario, sin embargo, la autoridad judicial tomando en cuenta las circunstancias del caso en particular podrá fijar las medidas provisionales y la obligación de dar alimentos, las cuales podrán modificarse cuando cambien las circunstancias de hecho que las determinaron. La obligación de dar alimentos puede suspender o cesar cuando se dan en la especie los supuestos previstos por la ley.</strong><br></h2>
            </div>
            <div class="col pulse animated collapse" id="collapsePenal">
            <h1 style="color: rgb(225,178,24);font-family: Thasadith, sans-serif;">Derecho Penal</h1>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 13px;">Derecho Penal<br></label>.&nbsp;<strong>El Derecho Penal se ubica dentro del Derecho Público toda vez que el Estado interviene activamente en la solución de conflictos buscando preservar el orden y la paz públicos. El Derecho Penal es el conjunto de normas jurídicas por medio de las cuales el Estado define las conductas u omisiones que constituyen delitos, así como las penas y/o medidas de seguridad para sancionar a quienes incurren en la comisión de esos delitos. Trataremos de forma general al Derecho Penal Sustantivo que es el conjunto de normas que definen los delitos, las penas y su aplicación.</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Legislación Aplicable en el Derecho Penal Sustantivo.</strong><br></label>&nbsp;<strong>En México se aplican el Código Penal Federal, los Códigos Penales Estatales, y otras legislaciones en la materia. El Código Penal Federal se aplica en toda la República para: delitos del orden federal; delitos que se inicien, preparen o cometan en el extranjero, cuando produzcan o se pretenda que produzcan efectos en todo el territorio de la República; delitos que se inicien, preparen o cometan en el extranjero siempre que un tratado vinculativo para México prevea la obligación de extraditar o juzgar y bajo ciertas condiciones no se extradite al probable responsable al país que lo haya requerido; y por delitos cometidos en los consulados mexicanos o en contra de su personal, cuando no hubieren sido juzgados en el país en que se cometieron.</strong><br><br><strong>Los Códigos Penales Estatales se aplicarán a los delitos que esos códigos regulen y que se comentan en el Estado de que se trate, o bien a los delitos que se inicien o cometan en un Estado distinto o en la Ciudad de México, cuando se trate de delitos permanentes o continuados que se sigan cometiendo dentro del Estado de que se trate. En estos códigos se establecen disposiciones relativas a la definición de delito; la descripción de las conductas u omisiones que constituyen delitos; las penas o medidas de seguridad para sancionar a quienes incurren en la comisión de esos delitos; los sujetos que intervienen en la comisión del delito; la responsabilidad penal; causas de exclusión de delito; tentativa, reincidencia; y otros.</strong><br><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Delito.&nbsp;</strong><br></label><strong>El delito es definido por el Código Penal Federal como el acto u omisión que sancionan las leyes penales. Algunos códigos estatales definen el delito como la conducta típica, antijurídica y culpable a la que se le atribuyen legalmente una o varias penas. Los delitos pueden ser instantáneos, permanentes o continuados.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">1.&nbsp;<strong>Los delitos instantáneos: son aquellos que se agotan en el mismo momento en que se han realizado todos los elementos de la descripción penal. Por ejemplo, el homicidio y el robo.&nbsp;</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">2.&nbsp;<strong>Los delitos permanentes: son aquellos cuya consumación se prolonga en el tiempo. Por ejemplo, el abandono de incapaz.&nbsp;</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">3.&nbsp;<strong>Los delitos continuados: son aquellos que se cometen con un mismo propósito delictivo y contra un mismo sujeto mediante varias conductas. Por ejemplo, el robo de una suma de dinero cometido por un empleado contra su patrón pero que no sustrae el total de la suma en un sólo día sino en varios. Se considera que alguien obra de forma dolosa cuando conociendo los elementos del delito o sus resultados, lo realiza. Por ejemplo: una persona conoce que comete homicidio al privar de la vida a otra persona y sabiéndolo apunta con un arma de fuego a una persona, acciona el arma y le da muerte a esa persona.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><strong>Y obra de forma culposa quien comete un delito que no previó o bien que siendo previsible o previó, confió que no se produciría, porque no tuvo el cuidado que debía. Por ejemplo: una persona que comete homicidio por tener en sus manos un arma de fuego, se la muestra a otra persona y de forma accidental acciona el gatillo, dando muerte a esa persona.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Delitos Federales.&nbsp;</strong><br></label><strong>De manera general hacemos mención de los delitos federales contemplados por el Código Penal Federal, la descripción y sanción de los mismos las podemos encontrar en dicho código. Son delitos federales: el ataque a las vías de comunicación, delitos contra la salud, trata de personas, falsificación de moneda, falsificación de documentos, delitos contra el medio ambiente, delitos contra la propiedad intelectual, robo de hidrocarburos, delitos relacionados con las armas de fuego, daños al patrimonio cultural, entre otros.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Delitos del Fuero Común.&nbsp;</strong><br></label><strong>Las entidades federativas a través de sus códigos penales, en sus disposiciones describen las conductas y omisiones constitutivas de delitos, así como sus respectivas sanciones. Esta clase de delitos se agrupan por el tipo de bien jurídico afectado que son: la vida y la integridad corporal, la libertad personal, la libertad y la seguridad sexual, el patrimonio, la familia, la sociedad, entre otros. Algunos de estos delitos son: homicidio, lesiones, feminicidio, aborto, abuso sexual, tráfico de menores, acoso sexual, violación, incesto, robo, fraude, abuso de confianza, extorsión, violencia familiar, violencia de género, incumplimiento de obligaciones de asistencia familiar, corrupción de menores, falsificación, entre otros.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Sujetos del Delito</strong><br></label><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">1. Sujeto Activo:&nbsp;<strong>Es la persona que realiza la conducta considerada como delito. Por ejemplo, quien comete el delito de secuestro, denominado secuestrador.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">2. Sujeto Pasivo:&nbsp;<strong>Es la persona titular del interés jurídico lesionado o puesto en peligro. También se le conoce con el nombre de víctima u ofendido. Por ejemplo, a quien se priva de la libertad en un secuestro.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Responsabilidad Penal.</strong><br></label><strong>Es la consecuencia jurídica derivada de la comisión de un delito. Quien comete un delito es responsable de cometerlo. Se consideran autores o partícipes del delito:</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">1.&nbsp;<strong> Los que preparen la realización de un delito.</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">2. <strong>El que realice el delito.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">3.&nbsp;<strong>Los que realicen el delito de forma conjunta.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">4.&nbsp;<strong>Los que lleven a cabo el delito valiéndose de otro.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">5.&nbsp;<strong>Los que determinen dolosamente a otro a cometerlo.</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">6.&nbsp;<strong>Los que dolosamente presten ayuda a otro para la comisión del delito</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">7.&nbsp;<strong>Los que con posterioridad a su ejecución auxilien al que lo cometió en cumplimiento a una promesa anterior al delito.</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 30px;padding-left: 30px;">8.&nbsp;<strong>Los que sin acuerdo previo intervengan en la comisión de un delito cuando no se pueda precisar el resultado que cada uno produjo.</strong></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><strong>Los autores o partícipes de un delito son responsables en la medida de su propia culpabilidad.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Imputabilidad.&nbsp;</strong><br></label><strong>La doctrina y los códigos penales estatales señalan que es penalmente imputable quien, al momento de realizar un delito, tiene capacidad de comprender que se trata de un delito y aun así decide realizarlo.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Inimputabilidad</strong><br></label><strong>La doctrina y algunos de los códigos penales de las entidades federativas disponen que estará excluido de delito quien, al momento de realizar el delito, no tenga capacidad de comprender que se trata de un delito, por padecer trastorno mental o bien desarrollo intelectual retardado. En estos casos el Juez a través de pruebas y dictámenes periciales valorará el grado de inimputabilidad y en base a esto impondrá las penas y medidas de seguridad que en su caso procedan.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Tentativa.&nbsp;</strong><br></label><strong>La tentativa se refiere a que puede suceder que una persona exteriorice la intención de cometer un delito realizando en parte o totalmente actos que deberían producir un determinado resultado o bien omitiendo aquellos actos que deberían evitar un determinado resultado, sin embargo, el resultado no se produce por causas ajenas a la voluntad de esa persona. Por ejemplo, una persona con un arma punzocortante en la mano, tiene la intención de lesionar a otra persona, se abalanza sobre esa persona, pero tropieza, el arma se cae y no se produce el resultado que quería que en este caso era lesionar a la persona. El código establece las circunstancias que deberá tomar en cuenta el Juez para imponer la pena de tentativa atendiendo el mayor o menor grado de aproximación al momento consumativo del delito. Existe también tentativa cuando el sujeto desiste de forma espontánea de la ejecución o impide la consumación del delito. En el mismo ejemplo del párrafo anterior, la persona que tiene la intención de lesionar a otra sosteniendo un arma punzocortante en la mano, decide no lesionar a la otra y lanza el arma al suelo. En este caso el Juez no impondrá pena o medida de seguridad por lo que a esto se refiere, sin embargo, podrá aplicar la pena o medida de seguridad que corresponda a actos ejecutados u omitidos que constituyan por sí mismos delitos.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Excluyente de Delito.&nbsp;</strong><br></label><strong>La exclusión de delito, es una figura que implica que no puede considerarse que existió un delito cuando se realicen ciertas conductas con el objetivo de proteger determinados bienes jurídicos propios o ajenos, o ante la inexistencia de la voluntad de cometer el delito, aunque se realice alguna de las conductas que lo integran. Los códigos penales establecen las causas de exclusión de delito. Por ejemplo, un sujeto en un transporte público acciona un arma, lesiona y da muerte a varios pasajeros, ante este hecho, uno de los pasajeros, combate ese acto delictivo y ante el inminente peligro de ser herido de gravedad o privado de la vida él u otros pasajeros, da un golpe, lesiona en la cabeza y da muerte al sujeto agresor. En este caso, el pasajero actuó en legítima defensa, no tenía la intención de dar muerte al agresor, esto es, de cometer el delito de homicidio. Algunos códigos disponen expresamente que las causas de exclusión del delito se pueden hacer valer de oficio en cualquier momento de la investigación o del proceso.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Reincidencia.&nbsp;</strong><br></label><strong>En términos generales podemos mencionar que el código penal se refiere a que existe reincidencia cuando un condenado por sentencia ejecutoria por cualquier Tribunal de la República o del extranjero comete un nuevo delito. Al reincidente se le incrementarán las sanciones que correspondan por el nuevo delito. En México, de acuerdo con datos del Instituto Nacional de Estadística y Geografía (INEGI), publicado en 2017, existe un alto porcentaje de delincuentes que son reincidentes, en algunos Estados de la República la reincidencia se da en un 44.9% de población que ha sido juzgada por la comisión de un delito antes de su reclusión actual.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Penas y Medidas de Seguridad.&nbsp;</strong><br></label><strong>Las penas y medidas de seguridad son las consecuencias jurídicas del delito. El objetivo de su existencia son la readaptación, resocialización, rehabilitación, reinserción o regeneración del delincuente sentenciado. El Estado busca además que la imposición de estas penas y medidas de seguridad a los delincuentes "sirvan de ejemplo" al resto de los integrantes de la sociedad. Se sanciona para que otros no cometan delitos. Entre las penas y medidas de seguridad establecidas en los códigos penales se encuentran: prisión; trabajo en favor de la comunidad; confinamiento; prohibición de ir a lugar determinado; sanciones pecuniarias (reparación del daño); decomiso de instrumentos, objetos y productos del delito; amonestación; apercibimiento; colocación de dispositivos de localización y vigilancia, entre otros.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Menores Infractores.&nbsp;</strong><br></label><strong>En el ámbito del derecho penal la edad es un factor de importancia, los menores de 18 años que realicen conductas tipificadas como delitos por los códigos penales, serán sometidos a disposiciones legales especiales para ellos. En México existe la Ley Nacional del Sistema Integral de Justicia Penal para Adolescentes que es de observancia en toda la República y se aplica a aquellos menores (adolescentes) entre 12 y 18 años de edad a quienes se les atribuya la comisión de una conducta tipificada como delito por las leyes penales.</strong><br></h2>
                <h2 style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-size: 15px;text-align: justify;padding-right: 15px;padding-left: 15px;"><label style="color: rgb(225,178,24);height: 12px;"><strong>Nuevo Sistema de Justicia Penal.&nbsp;</strong><br></label><strong>Como parte del Derecho Penal tenemos al Derecho Penal Procesal, que se refiere al conjunto de normas que regulan los procedimientos penales. Así tenemos el Nuevo Sistema de Justicia Penal, que fue incluido en el Sistema Jurídico Mexicano a partir de la reforma publicada el 18 de junio de 2008, a los artículos 16, 17, 18, 19, 20, 21 y 22; artículo 73 fracciones XXI y XXIII; artículo 115, fracción VII y artículo 123 apartado B fracción XIII de la Constitución Política de los Estados Unidos Mexicanos. Y entró en operación de manera gradual a nivel federal, por 7 etapas desde el año 2014 quedando implementada en todos los Estados de la República en el año 2016. En el Código Nacional de Procedimientos Penales se establece todo lo relativo al Sistema Penal Acusatorio para la impartición de justicia. Este Código está conformado por 2 apartados, uno que se refiere a las disposiciones generales y otro que se refiere al procedimiento.</strong><br></h2>
            </div>
        </div>
    </div>
</section>
<section data-aos="fade-up" id="contacto" class="about-us" style="padding-top: 0px;padding-bottom: 0px;height: 100px;">
<div class="container">
        <div class="row">
            <div class="col" style="border-bottom: 1px none rgb(0,56,105) ;">
                <h1 style="color: rgb(225,178,24);font-family: Thasadith, sans-serif;font-weight: 700;">Contáctanos</h1>
            </div>
        </div>
    </div>
</section>
<section data-aos="fade-up" id="about-2" class="about-us" style="padding-top: 50px;padding-bottom: 0px;background: url(&quot;assets/img/footer.jpg&quot;) center / cover no-repeat, rgba(225,178,24,0);">
<div class="container">
        <div class="row">
            <div class="col">
                <h1 style="font-family: Thasadith, sans-serif;font-size: 30px;color: rgb(0,56,105);">Hablemos</h1>
                <h1 style="font-family: Thasadith, sans-serif;font-size: 15px;color: rgb(0,0,0);">Ponte en contacto con nosotros y nos comunicaremos contigo lo más pronto posible.</h1>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div>
                    <div class="container-fluid" style="padding-right: 0px;padding-left: 0px;">
                        <form id="contactForm" action="javascript:void(0);" method="get"><input class="form-control" type="hidden" name="Introduction" value="This email was sent from www.awebsite.com"><input class="form-control" type="hidden" name="subject" value="Awebsite.com Contact Form"><input class="form-control" type="hidden" name="to" value="email@awebsite.com">
                            <div class="form-row">
                                <div class="col-md-6">
                                    <div id="successfail"></div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-12 col-md-6" id="message">
                                    <div class="form-group"><label for="from-phone" style="color: rgb(0,0,0);font-family: Thasadith, sans-serif;font-weight: 700;">Obligatorios</label><span class="required-input">*</span>
                                        <div class="input-group">
                                            <div class="input-group-prepend"></div><input class="form-control" type="text" id="from-name" name="name" required="" placeholder="Nombre Completo*" style="font-family: Thasadith, sans-serif;border-width: 0px;border-style: solid;border-radius: 8px;">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="input-group">
                                            <div class="input-group-prepend"></div><input class="form-control" type="text" id="from-email" name="email" required="" placeholder="Correo Electrónico*" style="border-radius: 8px;font-family: Thasadith, sans-serif;">
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-12 col-sm-6 col-md-12 col-lg-6">
                                            <div class="form-group">
                                                <div class="input-group">
                                                    <div class="input-group-prepend"></div><input class="form-control" type="text" id="from-phone" name="phone" required="" placeholder="Número Fijo" style="font-family: Thasadith, sans-serif;border-radius: 8px;">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-12 col-sm-6 col-md-12 col-lg-6">
                                            <div class="form-group">
                                                <div class="input-group">
                                                    <div class="input-group-prepend"></div><input class="form-control" type="text" id="from-phone-1" name="phone" required="" placeholder="Primary Phone" style="border-radius: 8px;font-family: Thasadith, sans-serif;">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group"><textarea class="form-control" id="from-comments" name="comments" placeholder="Asunto*" rows="5" style="border-radius: 8px;font-family: Thasadith, sans-serif;"></textarea></div>
                                    <div class="form-group">
                                        <div class="form-row">
                                            <div class="col"><button class="btn float-right" type="button" style="background: #003869;color: rgb(255,255,255);border-radius: 8px;width: 150px;">Enviar</button></div>
                                        </div>
                                    </div>
                                    <hr class="d-flex d-md-none">
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-12 col-md-6" id="message-1">
                                    <div class="form-group"><label for="from-phone" style="color: rgb(0,56,105);font-family: Thasadith, sans-serif;font-weight: 700;">Consulta nuestros&nbsp;<a href="#" style="color: rgb(0,56,105);">Términos y Condiciones</a>&nbsp;y&nbsp; el&nbsp;<a href="#" style="color: rgb(0,56,105);">Aviso de Privacidad.</a></label>
                                        <div class="input-group">
                                            <div class="input-group-prepend"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="modal fade" role="dialog" tabindex="-1" id="modal1">
                        <div class="modal-dialog modal-lg" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">Contact Information</h4><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                                </div>
                                <div class="modal-body">
                                    <form id="contactForm" action="javascript:void(0);" method="get"><input class="form-control" type="hidden" name="Introduction" value="This email was sent from www.awebsite.com"><input class="form-control" type="hidden" name="subject" value="Awebsite.com Contact Form"><input class="form-control" type="hidden" name="to" value="email@awebsite.com">
                                        <div class="form-row">
                                            <div class="col-md-6">
                                                <div id="successfail"></div>
                                            </div>
                                        </div>
                                        <div class="form-row">
                                            <div class="col-12 col-md-6" id="message">
                                                <h2 class="h4"><i class="fa fa-envelope"></i> Contact Us<small><small class="required-input">&nbsp;(*required)</small></small></h2>
                                                <div class="form-group"><label for="from-name">Name</label><span class="required-input">*</span>
                                                    <div class="input-group">
                                                        <div class="input-group-prepend"><span class="input-group-text"><i class="fa fa-user-o"></i></span></div><input class="form-control" type="text" id="from-name" name="name" required="" placeholder="Full Name">
                                                    </div>
                                                </div>
                                                <div class="form-group"><label for="from-email">Email</label><span class="required-input">*</span>
                                                    <div class="input-group">
                                                        <div class="input-group-prepend"><span class="input-group-text"><i class="fa fa-envelope-o"></i></span></div><input class="form-control" type="text" id="from-email" name="email" required="" placeholder="Email Address">
                                                    </div>
                                                </div>
                                                <div class="form-row">
                                                    <div class="col-12 col-sm-6 col-md-12 col-lg-6">
                                                        <div class="form-group"><label for="from-phone">Phone</label><span class="required-input">*</span>
                                                            <div class="input-group">
                                                                <div class="input-group-prepend"><span class="input-group-text"><i class="fa fa-phone"></i></span></div><input class="form-control" type="text" id="from-phone" name="phone" required="" placeholder="Primary Phone">
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-12 col-sm-6 col-md-12 col-lg-6">
                                                        <div class="form-group"><label for="from-calltime">Best Time to Call</label>
                                                            <div class="input-group">
                                                                <div class="input-group-prepend"><span class="input-group-text"><i class="fa fa-clock-o"></i></span></div><select class="form-control" id="from-calltime" name="call time">
                                                                    <optgroup label="Best Time to Call">
                                                                        <option value="Morning" selected="">Morning</option>
                                                                        <option value="Afternoon">Afternoon</option>
                                                                        <option value="Evening">Evening</option>
                                                                    </optgroup>
                                                                </select>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="form-group"><label for="from-comments">Comments</label><textarea class="form-control" id="from-comments" name="comments" placeholder="Enter Comments" rows="5"></textarea></div>
                                                <div class="form-group">
                                                    <div class="form-row">
                                                        <div class="col"><button class="btn btn-primary btn-block" type="reset"><i class="fa fa-undo"></i> Reset</button></div>
                                                        <div class="col"><button class="btn btn-primary btn-block" type="submit">Submit <i class="fa fa-chevron-circle-right"></i></button></div>
                                                    </div>
                                                </div>
                                                <hr class="d-flex d-md-none">
                                            </div>

                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="about-2" class="about-us" style="padding-top: 10px;padding-bottom: 10px;background: #003869;margin-top: 0px;">
    <div class="container">
        <div class="row">
            <div class="col-auto col-xl-2 align-self-center m-auto"><img class="img-fluid" src="assets/img/logo-footer.svg" style="filter: contrast(200%) grayscale(100%) invert(100%);width: 133px;"></div>
            <div class="col m-auto">
                <h1 style="font-family: Thasadith, sans-serif;font-size: 15px;color: rgb(255,255,255);font-weight: normal;">En Juan Sandoval y Asociados trabajamos para proteger tu patrimonio.</h1>
            </div>
        </div>
    </div>
</section>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
<script src="assets/js/script.min.js"></script>
<script src="assets/js/temas.js"></script>
</body>

</html>